[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
ndarray = "0.16.1"
num = "0.4.1"
regex = "1.11.1"
rustc-hash = "2.1.0"
